### ISSUE TITLE
I am getting this on installation

### ISSUE THREAD

**Issue by Pranavcartgeek** [jaynilsavani/laravel-country-state-city#3]
Problem 1
    - Root composer.json requires jaynilsavani/laravel-country-state-city 1.1.0 -> satisfiable by jaynilsavani/laravel-country-state-city[1.1.0].
    - jaynilsavani/laravel-country-state-city 1.1.0 requires php ^7.3 -> your php version (8.1.0) does not satisfy that requirement.

**Comment by jaynilsavani** [comment]
@Pranavcartgeek looking into it. Ideally, it should work as project v1.1.0 already have php: ^8.0.0. I will let you know.

**Comment by wankimmy** [comment]
hi @Pranavcartgeek , please run this command to install composer require jaynilsavani/laravel-country-state-city:1.0.0

**Comment by Pranavcartgeek** [comment]
I have used some other now . thank you for the response .
